The Last Task/flaskr/blueprints/games.py
from flask import (
    Blueprint, flash, g,
    redirect, render_template,
    request, url_for,
)
from flask.views import MethodView
from flasgger import swag_from

from ..model import Client, Game, Review, Developer, Publisher
from ..db import get_db, db_session

import datetime


bp_games = Blueprint('games', __name__, url_prefix='/games')


class GameAPI(MethodView):
    @staticmethod
    def get_user_review(game_id):
        ratings = [
            mark
            for mark, in
            Review.query.filter_by(game_id=game_id).with_entities(Review.rating)
        ]

        user_rating = None
        if ratings:
            user_rating = dict(
                average=sum(ratings) / len(ratings),
                numratings=len(ratings)
            )

        return user_rating

    @swag_from("specs_flasgger/auth.yml")
    def get(self, game_id):
        if game_id is None:
            games = Game.query.all()
            return render_template('games/games.html', games=games)
        else:
            game = Game.query.filter_by(id=game_id).first()
            client = g.client

            review = Review.query.filter_by(game=game, client=client).first()

            user_rating = GameAPI.get_user_review(game_id)

            return render_template('games/game.html', game=game, user_review=review, user_rating=user_rating)

    def post(self, game_id):
        if request.form['submit'] == 'review':
            rating = int(request.form['rating'])
            review_text = request.form['review']

            client = g.client
            game = Game.query.filter_by(id=game_id).first()

            prev_review = Review.query.filter_by(game=game, client=client).first()

            if prev_review:
                Review.query.filter_by(game=game, client=client).update(dict(
                    date_of_review=datetime.datetime.now(),
                    rating=rating,
                    review_text=review_text
                ))
                flash(u'Успешно обновлено.')
            else:
                review = Review(rating=rating, client=client, game=game, review_text=review_text)
                db_session.add(review)

            db_session.commit()

            user_rating = GameAPI.get_user_review(game_id)
            user_review = Review(rating=rating, client=client, game=game, review_text=review_text)

            return render_template('games/game.html', game=game, user_review=user_review, user_rating=user_rating)

        if request.form['submit'] == 'delete':
            game = Game.query.filter_by(id=game_id).first()

            db_session.delete(game)
            db_session.commit()

            flash(u'Игра {} была удалена.'.format(game.title))

            return redirect(url_for('games.game_api', game_id=None))


game_view = GameAPI.as_view('game_api')

bp_games.add_url_rule('/', defaults={'game_id': None}, view_func=game_view, methods=['GET'])
bp_games.add_url_rule('/<int:game_id>', view_func=game_view, methods=['GET', 'POST'])


@bp_games.route('/add', methods=('GET', 'POST'))
def add_game():
    if request.method == 'POST':
        title = request.form['title']
        release_date = request.form['release_date']
        developer = request.form['developer']
        publisher = request.form['publisher']
        pic_url = request.form['pic_url']

        game = Game(
            title=title,
            release_date=release_date,
            developer=Developer.get_or_create(name=developer, session=db_session),
            publisher=Publisher.get_or_create(name=publisher, session=db_session),
            pic_url=pic_url,
        )

        db_session.add(game)
        db_session.commit()

        flash(u'Game {} has been added.'.format(title))

        return redirect(url_for('games.game_api', game_id=None))
    else:
        return render_template('games/add_form.html')

The Last Task/flaskr/templates/games/add_form.html
{% extends 'base.html' %}


{% block header %}
	<h2>Добавление игры</h2>
{% endblock %}


{% block content %}
    <form method="post">
        <div>
            <label for="title">Название</label>
            <input type="text" id="title" name="title" required />
        </div>

        <br>

        <div>
            <label for="release_date">Первая дата выхода</label>
            <input type="date" id="release_date" name="release_date" required />
        </div>

        <br>

        <div>
            <label for="developer">Разработчик</label>
            <input type="text" id="developer" name="developer" required />
        </div>

        <br>

        <div>
            <label for="publisher">Издатель</label>
            <input type="text" id="publisher" name="publisher" required />
        </div>

        <br>

        <div>
            <label for="pic_url">Ссылка на изображение</label>
            <input type="url" id="pic_url" name="pic_url" />
        </div>

        <br>

        <br>

        <button type="submit">Добавить</button>
    </form>
{% endblock %}

The Last Task/flaskr/templates/games/game.html
{% extends 'base.html' %}


{% block header %}
    <h2>{{ game.title }}</h2>

    {% if game.pic_url %}
        <img src="{{ game.pic_url }}" alt="{{ game.title }}" style="max-width: 500px; max-height: 500px;">
    {% endif %}
{% endblock %}


{% block content %}
    <ul>
        <li>Разработчик: {{ game.developer }}</li>
        <li>Издатель: {{ game.publisher }}</li>
        <li>Дата выхода: {{ game.release_date }}</li>

        {% if user_rating %}
            <br>
            <li>Рейтинг пользователей: {{ user_rating.average }}</li>
            <li>Всего оценок: {{ user_rating.numratings }}</li>
        {% endif %}
    </ul>

    {% if not g.client %}
        <h3>Войдите в аккаунт, чтобы оставить отзыв</h3>
    {% else %}
        <h3>Отзыв:</h3>
        <form method="POST">

          <div>
            Оценка:
            <input type="radio" id="ratingChoise1"
             name="rating" value="1" {{ "checked" if user_review.rating == 1 else "" }} required>
            <label for="ratingChoise1">1</label>

            <input type="radio" id="ratingChoise2"
             name="rating" value="2" {{ "checked" if user_review.rating == 2 else "" }}>
            <label for="ratingChoise2">2</label>

            <input type="radio" id="ratingChoise3"
             name="rating" value="3" {{ "checked" if user_review.rating == 3 else "" }}>
            <label for="ratingChoise3">3</label>

            <input type="radio" id="ratingChoise4"
             name="rating" value="4" {{ "checked" if user_review.rating == 4 else "" }}>
            <label for="ratingChoise4">4</label>

            <input type="radio" id="ratingChoise5"
             name="rating" value="5" {{ "checked" if user_review.rating == 5 else "" }}>
            <label for="ratingChoise5">5</label>
          </div>

          <p>Комментарий:</p>
          <div>
            <textarea id="review" name="review" style="resize: none"
              rows="5" cols="35" placeholder="здесь может быть ваш комментарий">{{ user_review.review_text }}</textarea>
          </div>

          <br>


          <button type="submit" name="submit" value="review" style="width: 110px">{{ "Изменить" if user_review else
              "Отправить"
              }}</button>
        </form>

        <br>

        <form method="POST">
            <button type="submit" name="submit" value="delete" style="width: 110px">Удалить игру</button>
        </form>
    {% endif %}
{% endblock %}

The Last Task/flaskr/templates/games/games.html
{% extends 'base.html' %}


{% block header %}
	<h2>Список игр</h2>
	<a href="{{ url_for('games.add_game') }}">| Add |</a>
{% endblock %}


{% block content %}
	<ul>
		{% for game in games %}
			<li><a href="{{ url_for('games.game_api', game_id=game.id) }}">{{ game.title }}</a>
		{% endfor %}
	</ul>
{% endblock %}